from sujsim.core.spells.buff import Buff
from sujsim.core.spells.magic_school import MagicSchool
from sujsim.core.stats.item_stats import ItemStats

ARCANE_BLAST = Buff(db_id=30451, name='Arcane Blast', duration=8, max_stacks=3)
ARCANE_MADNESS = Buff(db_id=37444, name='Arcane Madness', duration=6, stats=ItemStats(spell_power=70))
ARCANE_POWER = Buff(db_id=12042, name='Arcane Power', duration=15)
PRESENCE_OF_MIND = Buff(db_id=12043, name='Presence of Mind', duration=100)
ICY_VEINS = Buff(db_id=12472, name='Icy Veins', duration=20)
COMBUSTION = Buff(db_id=29977, name='Combustion', duration=2000, max_stacks=20)
COMBUSTION_CRITS = Buff(db_id=7729977, name='Combustion', duration=2000, max_stacks=3)
SILVER_CRESCENT = Buff(db_id=35163, name='Silver Crescent', duration=20, stats=ItemStats(spell_power=155))
SERPENT_COIL = Buff(db_id=30720, name='Serpent Coil', duration=15, stats=ItemStats(spell_power=225))
CLEARCAST = Buff(db_id=12536, name='Clearcasting', duration=15)
BLOODLUST = Buff(db_id=2825, name='Bloodlust', duration=40)
POWER_INFUSION = Buff(db_id=10060, name='Power Infusion', duration=15)
INNERVATE = Buff(db_id=19288, name='Innervate', duration=20)
MANA_TIDE = Buff(db_id=39609, name='Mana Tide', duration=12)
MANA_SPRING_TOTEM = Buff(db_id=25570, name='Mana Spring', stats=ItemStats(mp_5=50), duration=120)
SPELLSTRIKE = Buff(db_id=32106, name='Lesser Spell Blasting', duration=10, stats=ItemStats(spell_power=92))
EYE_OF_MAGTHERIDON = Buff(db_id=34747, name='Recurring Power', duration=10, stats=ItemStats(spell_power=170))
RESTRAINED_ESSENCE = Buff(db_id=28779, name='Essence of Sapphiron', duration=20, stats=ItemStats(spell_power=130))
QUAGMIRRANS_EYE = Buff(db_id=33370, name='Spell Haste', duration=6)
UNSTABLE_CURRENTS = Buff(db_id=38348, name='Unstable Currents', duration=15, stats=ItemStats(spell_crit_rating=190))
LIGHTNING_CAPACITOR = Buff(db_id=37657, name='Lightning Capacitor', duration=200, max_stacks=3)
BERSERKING = Buff(db_id=20554, name='Berserking', duration=10)
MQG = Buff(db_id=19339, name='Mind Quickening Gem', stats=ItemStats(spell_haste_rating=330), duration=20)
BLUE_DRAGON = Buff(db_id=23684, name='Aura of the Blue Dragon', duration=15)
SCRYERS_BLOODGEM = Buff(db_id=35337, name='Spell Power', duration=15, stats=ItemStats(spell_power=150))
CRYSTAL_TALISMAN = Buff(db_id=32355, name='Focused Power', duration=20, stats=ItemStats(spell_power=104))
PENDANT_VIOLET_EYE = Buff(db_id=29601, name='Pendant of the Violet Eye', duration=20)
ENLIGHTENMENT = Buff(db_id=35095, name='Enlightenment', stats=ItemStats(mp_5=21), duration=20, max_stacks=100)
VENGEANCE_ILLIDARI = Buff(db_id=33662, name='Arcane Energy', duration=15, stats=ItemStats(spell_power=120))
ETERNAL_SAGE = Buff(db_id=35084, name='Band of Eternal Sage', duration=10, stats=ItemStats(spell_power=95))
SPELL_BLASTING = Buff(db_id=25906, name='Spell Blasting', duration=10, stats=ItemStats(spell_power=132))
SKULL_GULDAN = Buff(db_id=40396, name='Fel Infusion', duration=20)
SHRUNKEN_HEAD = Buff(db_id=43712, name='Mojo Madness', duration=20, stats=ItemStats(spell_power=211))
NAARU_SLIVER = Buff(db_id=45042, name='Power Circle', duration=15, stats=ItemStats(spell_power=320))
DRUMS_OF_BATTLE = Buff(db_id=35476, name='Drums of Battle', duration=30)
DRUMS_OF_WAR = Buff(db_id=35475, name='Drums of War', duration=30, stats=ItemStats(spell_power=30))
DRUMS_OF_RESTORATION = Buff(db_id=35478, name='Drums of Restoration', duration=30)
DESTRUCTION_POTION = Buff(db_id=28508, name='Destruction', duration=15)
FLAME_CAP = Buff(db_id=28714, name='Flame Cap', duration=60, stats=ItemStats(spell_power=80, impacted_schools=[MagicSchool.FIRE]))
DARKMOON_CRUSADE = Buff(db_id=39438, name='Aura of the Crusade', duration=10, max_stacks=10, stats=ItemStats(spell_power=8))
SPELL_POWER_BONUS = Buff(db_id=37619, name='Spell Power Bonus', duration=15, stats=ItemStats(spell_power=110))
ASHTONGUE_TALISMAN = Buff(db_id=40482, name='Insight of the Ashtongue', duration=5)
CALL_OF_THE_NEXUS = Buff(db_id=34320, name='Call of the Nexus', duration=10)

INSIGHTFUL_EARTHSTORM_COOLDOWN = Buff(db_id=27521, name='Insightful Earthstorm Cooldown', duration=15)

DEBUG = Buff(db_id=-777, name='Debug', stats=ItemStats(spell_crit_rating=8000))
